[tool.poetry]
name = "django-prj"
version = "0.1.0"
description = ""
authors = ["yodd <creatyoo0491@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
